columns:
  having_ip_address: int
  url_length: int
  shortening_service: int
  having_at_symbol: int
  double_slash_redirecting: int
  prefix_suffix: int
  having_sub_domain: int
  ssl_state: int
  domain_registration_length: int
  favicon: int
  port: int
  https_token: int
  request_url: int
  url_of_anchor: int
  links_in_tags: int
  sfh: int
  submitting_to_email: int
  abnormal_url: int
  redirect: int
  on_mouseover: int
  right_click: int
  popup_window: int
  iframe: int
  dns_record: int
  age_of_domain: int
  web_traffic: int
  page_rank: int
  google_index: int
  links_pointing_to_page: int
  statistical_report: int
  label: int

numerical_columns:
  - having_ip_address
  - url_length
  - shortening_service
  - having_at_symbol
  - double_slash_redirecting
  - prefix_suffix
  - having_sub_domain
  - ssl_state
  - domain_registration_length
  - favicon
  - port
  - https_token
  - request_url
  - url_of_anchor
  - links_in_tags
  - sfh
  - submitting_to_email
  - abnormal_url
  - redirect
  - on_mouseover
  - right_click
  - popup_window
  - iframe
  - dns_record
  - age_of_domain
  - web_traffic
  - page_rank
  - google_index
  - links_pointing_to_page
  - statistical_report
  - label
